# Generated by Django 2.2.7 on 2019-11-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsRoominfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us_roomname', models.CharField(max_length=40)),
                ('us_roomtime', models.CharField(max_length=40)),
                ('us_roompassword', models.CharField(max_length=40)),
                ('us_use', models.IntegerField()),
            ],
            options={
                'db_table': 'us_roominfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsUser',
            fields=[
                ('us_id', models.AutoField(primary_key=True, serialize=False)),
                ('us_name', models.CharField(max_length=50, unique=True)),
                ('us_email', models.CharField(max_length=50)),
                ('us_department', models.CharField(max_length=50)),
                ('us_roomname', models.CharField(max_length=50)),
                ('us_roomtime', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'us_user',
                'managed': False,
            },
        ),
    ]
